### ISSUE TITLE
Program the "Dispose pizza" button of the pizzeria minigame

### ISSUE THREAD

**Issue by Ironwolf1212** [MCV-Univalle/TalesOfEtrya#35]
This button should make the player lose some HP and dispose the current pizza

**Comment by DianaKToro** [comment]
https://drive.google.com/file/d/13WXhpRKUWmL_KLcLDGpVZHG8RMSutsGv/view?usp=sharing

**Comment by Sof1a** [comment]
Changed the pipeline from Done to Closed for Tales of Etrya
