### ISSUE TITLE
Proposal Minigame.

### ISSUE THREAD

**Issue by ALDE308** [MCV-Univalle/TalesOfEtrya#38]
A proposal for the mini-game is being developed.
-The mini-game must restore the player's missing life points
-The mini-game should contain two main puzzle sections and the doctor's office
-The puzzle will be an introduction to the basic parts of the body and the amount of life points the player will earn will be 10% of the total missing
-The doctor's office will have three internal sections which will be: emergency, doctor's office and pharmacy
-Emergency section: Access will be when the player has 10% or less of his total life points
-Doctor's office section: The player has access at any time to recover life points
-Pharmacy section: The player must claim the medicine prescribed by the doctor once he leaves one of the two previous sections
-Scope for the 2019-2 semester: The scope is to make the puzzle section and the pharmacy section

**Comment by edwingamboa** [comment]
Criterios de aceptacion?
