### ISSUE TITLE
Making the objects

### ISSUE THREAD

**Issue by DianaKToro** [MCV-Univalle/TalesOfEtrya#41]
Create the assets if they are not created yet.

**Comment by sacuto310** [comment]
These are the assets we found at the main proyect, they will be located correctly in the minigame and will be the vocabulary to be used, it is possible to use more assets to expand the vocabulary list  ![Estatues.jpeg](https://images.zenhubusercontent.com/5e41a00a69d880add3f1226b/28699cf2-e9c2-441d-b558-d06b0839b8cd)
![Props.jpeg](https://images.zenhubusercontent.com/5e41a00a69d880add3f1226b/5c7205b4-1b08-48dc-a881-3925e5ef1d53)
![Table and chairs.jpeg](https://images.zenhubusercontent.com/5e41a00a69d880add3f1226b/c691b69b-a981-4d28-9bdf-d97b76d80517)
![Chairs.jpeg](https://images.zenhubusercontent.com/5e41a00a69d880add3f1226b/0cf8cf46-1752-4dd8-932f-d255f047e176)

**Comment by Sof1a** [comment]
Changed the pipeline from Done to Closed fot Tales of Etrya

**Comment by sacuto310** [comment]
![EvidenciaPoly.png](https://images.zenhubusercontent.com/5e41a00a69d880add3f1226b/2d6338af-21b5-470d-88c3-b73db330e8d7)

Using the asset store, very good material was found from which some objects were selected that had the same theme and aesthetics, the opinion of others is expected to proceed to place them in the minigame
