### ISSUE TITLE
Create a panel 

### ISSUE THREAD

**Issue by Ironwolf1212** [MCV-Univalle/TalesOfEtrya#46]
![dsasdsadsdasdasdadsa](https://user-images.githubusercontent.com/50991272/76251280-c90a8800-6214-11ea-8493-e39210e29a44.png)
![fondo este](https://user-images.githubusercontent.com/50991272/76250549-90b67a00-6213-11ea-99f1-d26cbeb6245f.png)
Create a panel behind the ingredient´s buttons so that there is a synergy between the background color and the color of the disabled buttons

**Comment by edwingamboa** [comment]
Descripción?

**Comment by edwingamboa** [comment]
Descripción?

**Comment by Sof1a** [comment]
Colocar imagen que muestre los cambios que se le hicieron.

**Comment by Ironwolf1212** [comment]
![azwesxrdctfvgujhnk](https://user-images.githubusercontent.com/50991272/76893288-16f93e80-685a-11ea-9f55-26d99948709b.png)

**Comment by Sof1a** [comment]
Changed the pipeline from Review/QA to Done for Tales of Etrya

**Comment by Sof1a** [comment]
Changed the pipeline from Review/QA to Closed for Tales of Etrya
