### ISSUE TITLE
2d Johnny design 

### ISSUE THREAD

**Issue by ALDE308** [MCV-Univalle/TalesOfEtrya#48]
-I'm waiting for david to help me design johnny in 2d

**Comment by ALDE308** [comment]
-Se obtuvo el diseño de Jhonny por parte de David
![Diseño jhonny](https://user-images.githubusercontent.com/53026371/77671248-50feca80-6f55-11ea-8941-57fd0da487f1.jpeg)

**Comment by Sof1a** [comment]
Changed the pipeline from Done to Closed for Tales of Etrya
