### ISSUE TITLE
Initial Screen Layout

### ISSUE THREAD

**Issue by ALDE308** [MCV-Univalle/TalesOfEtrya#49]
-The design was updated with an original image of the game, this image was found in the Assets and was edited, then the two images that are considered better: 
- 1:
![HospitalToEColaboracio2 0](https://user-images.githubusercontent.com/53026371/77670262-f31db300-6f53-11ea-940f-cb97ded5e9fd.png)

- 2:
![HospitalToEColaboracio1 0](https://user-images.githubusercontent.com/53026371/77670301-02046580-6f54-11ea-8a1e-19ea31eae653.png)

-Designs with other colors which the group members did not like very much, are added for feedback or comparison with the first two  
- 1:
![HospitalToECompleto1 1](https://user-images.githubusercontent.com/53026371/77670662-81923480-6f54-11ea-975e-d4b49bde0081.jpg)

- 2:
![HospitalToECompletoSinBordes1 2](https://user-images.githubusercontent.com/53026371/77670773-a4244d80-6f54-11ea-8e8d-5f2aa9d1c03a.png)

- 3:
![HospitalToECompletoConBordesCafe1 6](https://user-images.githubusercontent.com/53026371/77670819-b9997780-6f54-11ea-958b-8175d2030fd0.png)

- 4:
![HospitalToECompletoSinBordesCafe1 5](https://user-images.githubusercontent.com/53026371/77670909-d2a22880-6f54-11ea-8444-23c283cdeb8c.png)

**Comment by edwingamboa** [comment]
It is not clear why this issue is ready to be closed?

**Comment by Sof1a** [comment]
Changed the pipeline from Done to Review for Tales of Etrya for the colors palette

**Comment by Sof1a** [comment]
Changed the pipeline from Done to Closed for Tales of Etrya
It looks better
