### ISSUE TITLE
Stop showing the ingredients in each order if they are not neccesary

### ISSUE THREAD

**Issue by Ironwolf1212** [MCV-Univalle/TalesOfEtrya#55]
![zwsxedcrtfvgbyh](https://user-images.githubusercontent.com/50991272/78599410-b173ee80-7816-11ea-8672-22981f2b043d.png)
If the RNG for the needed ingredients gets a 0 in any ingredient, it should not show the ingredient´s name and it should hide it instead

**Comment by LeidyJr** [comment]
Ya fue socializado anteriormente, revisado.
