### ISSUE TITLE
Writing the ToE paper

### ISSUE THREAD

**Issue by DianaKToro** [MCV-Univalle/TalesOfEtrya#56]
Iterate the thematic analysis and writing of the document

**Comment by DianaKToro** [comment]
![image.png](https://images.zenhubusercontent.com/5cf97ae8b57ccc6be2abd1b0/f0ff15fa-69bf-4711-a1bb-ecc75599360d)

**Comment by DianaKToro** [comment]
The second iteration of the results of the thematic analysis was completed

**Comment by DianaKToro** [comment]
Organize the information of the second iteration of the results of the thematic analysis
![image.png](https://images.zenhubusercontent.com/5cf97ae8b57ccc6be2abd1b0/ccd64740-11ea-4e30-b40a-453a60f89a55)

**Comment by DianaKToro** [comment]
Update of the graph containing the thematic analysis with the results of the interactions with the Optimal Workshop tool

![Graphics Challenges and Recommendations ToE.png](https://images.zenhubusercontent.com/5cf97ae8b57ccc6be2abd1b0/d8c3695d-0f03-458d-8052-cc4c09f310d3)

**Comment by LeidyJr** [comment]
Revisado y aprobado.

**Comment by DianaKToro** [comment]
Final graphics

![Graphics Challenges and Recommendations ToE.png](https://images.zenhubusercontent.com/5cf97ae8b57ccc6be2abd1b0/94eb8015-f763-4013-9119-2c91bc850796)


![Recommendations.png](https://images.zenhubusercontent.com/5cf97ae8b57ccc6be2abd1b0/5cf333dd-25db-4c07-a049-5caa1b989ffb)


![Challenges.png](https://images.zenhubusercontent.com/5cf97ae8b57ccc6be2abd1b0/8d07f4b9-4301-4f29-a893-91e90e3beb8c)

**Comment by DianaKToro** [comment]
Creation of a new version of the paper. Pending review to finish the findings of the challenges and the conclusion, in order to see if it is well written and elaborated. 

![image.png](https://images.zenhubusercontent.com/5cf97ae8b57ccc6be2abd1b0/528875ad-dab6-4e09-87c1-dad6d977a8ef)

**Comment by Sof1a** [comment]
Changed the pipeline from Done to Closed for Tales of Etrya

**Comment by DianaKToro** [comment]
Notification of acceptance of the ToE paper

![image.png](https://images.zenhubusercontent.com/5cf97ae8b57ccc6be2abd1b0/ba8c3237-1594-46d6-9dc6-1064e9bbaf71)
