### ISSUE TITLE
Improve the interface

### ISSUE THREAD

**Issue by sacuto310** [MCV-Univalle/TalesOfEtrya#57]
the last interface was generic and lame, improve with assets to make more natural the user interface, more friendly and according to the game's style ![Evidence.png](https://images.zenhubusercontent.com/5e41a00a69d880add3f1226b/b9076e64-e157-4831-8579-c06386e53b28)

**Comment by sacuto310** [comment]
![Evidence.png](https://images.zenhubusercontent.com/5e41a00a69d880add3f1226b/ca9bcf85-b944-48ff-8e45-05cb8023880c)
Improved interface according to the recomendations and according to the actually game world.

**Comment by Sof1a** [comment]
It looks great
Changed the pipeline from Done to Closed for Tales of Etrya
