### ISSUE TITLE
Get the body parts from Jhonny's design

### ISSUE THREAD

**Issue by ALDE308** [MCV-Univalle/TalesOfEtrya#60]
-The body parts are obtained to be the pieces of the puzzle, this from the design that David made of Jhonny

**Comment by ALDE308** [comment]
-The body parts were obtained as pieces of the puzzle
![evidenciaPartes](https://user-images.githubusercontent.com/53026371/78832037-39413080-79b0-11ea-8a2f-86017476bfde.PNG)

**Comment by ALDE308** [comment]
-The two options for the silhouette of the puzzle are shown
-The first is the option to have the silhouette in gray
![Jhonny1Gris](https://user-images.githubusercontent.com/53026371/79894670-6a1b5f80-83cb-11ea-8456-b512647193c9.png)

-The second is with the same gray scale but with the silhouette blurred
![Jhonny1GrisDifuminado](https://user-images.githubusercontent.com/53026371/79894776-91722c80-83cb-11ea-9f15-a401ba33a205.png)

**Comment by LeidyJr** [comment]
Revisado, puede cerrarse. 
(Buena opción hacerlo degradado).

**Comment by ALDE308** [comment]
-Silhouette for the puzzle faded and with the lightest color
![Jhonny1Difuminado](https://user-images.githubusercontent.com/53026371/81227284-ca0c2b80-8fb1-11ea-8ddf-95cc419c1e57.png)

**Comment by Sof1a** [comment]
I like it! 
Changed the pipeline from Done to Closed for Tales of Etrya

**Comment by ALDE308** [comment]
-Silhouette for the puzzle faded and with the lightest color
![Jhonny1Difuminado2](https://user-images.githubusercontent.com/53026371/82495459-bdf39400-9ab0-11ea-904b-9da1d3f04017.png)

**Comment by Sof1a** [comment]
Changed the pipeline from Done to Review/QA for Tales of Etrya

**Comment by ALDE308** [comment]
-New design by Jhonny
![JhonnyAcostado](https://user-images.githubusercontent.com/53026371/92136304-7d0a5b80-edd1-11ea-8599-ff081b68dbbf.png)



-Silhouette that will be used to put the puzzle together 
![JhonnyAcostadoDifuminado](https://user-images.githubusercontent.com/53026371/92136335-85629680-edd1-11ea-9bf8-e6ba6fc3f8e9.png)

**Comment by ALDE308** [comment]
-The body parts were taken out to be the pieces of the puzzle

![image](https://user-images.githubusercontent.com/53026371/93389607-fecaa200-f831-11ea-8309-7f6997f82205.png)

**Comment by Daniel0205** [comment]
Ready to be closed.
