### ISSUE TITLE
Add the "Pizza counter"

### ISSUE THREAD

**Issue by Ironwolf1212** [MCV-Univalle/TalesOfEtrya#66]
![gfdddd](https://user-images.githubusercontent.com/50991272/81232366-62a6a980-8fba-11ea-852e-059a3ac8b3d2.png)
Add a counter to keep track of how many pizza are correctly prepared and delivered

**Comment by Sof1a** [comment]
Changed the pipeline from Done to Closed for Tales Of Etrya
