### ISSUE TITLE
 Determining the vocabulary

### ISSUE THREAD

**Issue by sacuto310** [MCV-Univalle/TalesOfEtrya#69]
The provisional vocabulary of the fire station project is:
Sofá: Couch
Cama: Bed
Sillón: Armchair
Estantería: Shelving
Mesa: Table
Lámpara: Lamp
Planta: Plant
Silla: Chair
Bote de basura: Trash can
Televisión: Television
Cortinas: Curtains 
Cuadro: Picture
Camarote: Cabin
Libros: Books
Armario: Wardrobe
Puerta: Door
Escoba: Broom
Trapeador: Mop
Equipo de sonido: Stereo
Refrigerador: Fridge

**Comment by sacuto310** [comment]
![Aprovement.jpeg](https://images.zenhubusercontent.com/5e41a00a69d880add3f1226b/547a7132-ec34-456b-b679-b5807e6058b5)

English teacher approval

**Comment by Sof1a** [comment]
Changed the pipeline from Done to Closed for Tales of Etrya
