### ISSUE TITLE
Create a pause menu

### ISSUE THREAD

**Issue by Ironwolf1212** [MCV-Univalle/TalesOfEtrya#72]
![Pause menu](https://user-images.githubusercontent.com/50991272/84186545-4df48000-aa56-11ea-8f2a-5d1fda8cf7cc.png)

Move the insructions button to the pause menu and standardize its format for all the other minigames (try to keep the ToE style for this menu)

![Menú](https://user-images.githubusercontent.com/50991272/93358083-b053de00-f806-11ea-87c8-8c096bb95e71.png)
This is the actual prototype of the pause menu, where both the "instructions" and "settings" buttons are customizable for each minigame, the "exit" button is mandatory

**Comment by Daniel0205** [comment]
Ready to be closed.
