### ISSUE TITLE
Make corrections to the paper

### ISSUE THREAD

**Issue by DianaKToro** [MCV-Univalle/TalesOfEtrya#75]
According to the reviewers' suggestion, the correction is made in the paper. After that, the submission is made for publication in the magazine of the event.

**Comment by DianaKToro** [comment]
The corrections suggested by the evaluators were made and the new document was sent.

![imagen.png](https://images.zenhubusercontent.com/5cf97ae8b57ccc6be2abd1b0/f4edfcc1-f4ee-4882-ad3c-d63904b1dba0)

**Comment by Daniel0205** [comment]
Ready to be closed.
