### ISSUE TITLE
Make the presentation for the conference

### ISSUE THREAD

**Issue by DianaKToro** [MCV-Univalle/TalesOfEtrya#76]
To expose the work done in the paper must make the presentation for the VI Ibero-American Conference of HCI

**Comment by DianaKToro** [comment]
![image.png](https://images.zenhubusercontent.com/5cf97ae8b57ccc6be2abd1b0/3a7e1d6b-b8e2-4f25-9ed9-6c8d3042331d)

**Comment by Daniel0205** [comment]
Ready to be closed.
