### ISSUE TITLE
Proposals of correction to level 1

### ISSUE THREAD

**Issue by ManuelBermudezMontes** [MCV-Univalle/TalesOfEtrya#77]
-The analog which control the camera feels pretty slow,
-The firsts objectives related with the old woman are somehow linear, I mean the order are one by one instead of choosing which one to do first
-The conversations with some npc are pretty straightforward, there are no reasons or story behind the requests
-There should be an action button which allow the player to interact with the enviroment in a more comfortable way, instead of touch the items on screen.

My proposals are to modify this behaviors in the game.

**Comment by ManuelBermudezMontes** [comment]
![dialog1.jpg](https://images.zenhubusercontent.com/5f5684a55069e319620270e5/7a9c7b34-52d6-4d45-ab66-df9d429ba729)![dialog2.jpg](https://images.zenhubusercontent.com/5f5684a55069e319620270e5/e7d72f6e-d630-4250-afe4-7cb7b4150b53)![dialog3.jpg](https://images.zenhubusercontent.com/5f5684a55069e319620270e5/e1ff4163-f3d5-4c87-808c-e1bba1710267)![actionbutton.jpg](https://images.zenhubusercontent.com/5f5684a55069e319620270e5/171dc9ef-ca78-4b9a-8ec6-0001e3b53ba5)![rightanalog.jpg](https://images.zenhubusercontent.com/5f5684a55069e319620270e5/cb6fa160-794e-46da-92f2-f938ed866fde)![objectives.jpg](https://images.zenhubusercontent.com/5f5684a55069e319620270e5/30dee1f1-f1c3-4582-a04d-221813fcbfbd)

**Comment by Daniel0205** [comment]
Ready to be closed.
