### ISSUE TITLE
Minijuego Johan's Tech Shop

### ISSUE THREAD

**Issue by Johandarkness** [MCV-Univalle/TalesOfEtrya#79]
Es mi idea de un minijuego para el nivel 1 de ToE, adjunto imagen con el texto en inglés y gráficos de cómo sería la interfaz. 

Johan's Tech Shop como lo dice su nombre es una tienda de componentes tecnológicos de cualquier clase, la idea del minijuego es que el jugador aprenda el vocabulario que se usa a la hora de comprar componentes para su día a día en inglés, el vocabulario usado contiene las palabras más usadas en las tiendas de componentes.

El minijuego iría así, el jugador llega a la tienda y el dueño le encarga con una misión, la cual es armar un pc que tenga unas partes específicas y con su precio, se le dará un presupuesto al jugados, así que cuando use partes malas se le descontará del presupuesto, si el precio de los items se pasa del presupuesto el jugador tendrá que reiniciar la primera parte del juego.

la segunda parte sería ya con los items seleccionados empezar a armar el pc, donde sería un click-n-drawn o un click y arrastra, donde llevaría los objetos a su determinado puesto, si falla provocará un "corto circuito" y se verá forzado a repetir la parte 2, si después de varios reincios el jugador sigue equivocándose pasará a la parte 3, donde el pc le quedará malo y tendrá que reiniciar.  

la parte tres sería entregarle el pc al dueño y el NPC  "revisa" el pc, si le quedó bueno lo pasa y el minijuego termina como éxito, sino un fail y se reinicia en la parte 3. 

adjunto los gráficos y la explicación en inglés como jpg 
![minijuego 1.jpg](https://images.zenhubusercontent.com/5f56cab30ed45b7aab2e6ade/cf6c7483-7ecc-433e-b371-194885bda2b5)
![minijuego 2.jpg](https://images.zenhubusercontent.com/5f56cab30ed45b7aab2e6ade/09fdb276-2bc0-4ffd-a8ca-a6b6078fbabb)

**Comment by Daniel0205** [comment]
Not accepted, the idea must be restructured due to the dinamic of the minigame is similar to pizzery mini-game.
